const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

const formatCurrency = (amount) => `INR ${parseFloat(amount || 0).toFixed(2)}`;

/**
 * Generate Multi-Page Event Summary Report (No 15-row truncation!)
 */
const generateEventReport = (data, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4', autoFirstPage: true });
  doc.pipe(res);

  const { event, participants = [], payments = [], feedbackSummary = {} } = data;

  // Header Banner
  doc.rect(0, 0, doc.page.width, 90).fill('#1e3a8a');
  doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text('COLLEGE EVENT MANAGEMENT SYSTEM', 40, 24);
  doc.fontSize(11).font('Helvetica').text('Official Comprehensive Event & Accreditation Report', 40, 50);
  doc.fontSize(9).font('Helvetica-Oblique').text('Plan. Participate. Celebrate.  •  Generated by Smart CEMS', 40, 68);

  doc.moveDown(3);

  // Event Basic Details Block
  doc.rect(40, 105, doc.page.width - 80, 115).fillAndStroke('#f8fafc', '#cbd5e1');
  doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text(event.title || 'Untitled Event', 55, 118, { width: 500 });

  doc.fontSize(9.5).font('Helvetica').fillColor('#334155');
  doc.text(`Category: ${event.category || 'General'}    |    Department: ${event.department || 'All Departments'}`, 55, 142);
  doc.text(`Date: ${event.date}   |   Time: ${event.startTime || ''} - ${event.endTime || ''}`, 55, 158);
  doc.text(`Venue: ${event.venue || 'Campus'} ${event.room_number ? `(${event.room_number})` : ''}`, 55, 174);
  doc.text(`Organizer: ${event.organizerName || 'Faculty Convener'} (${event.contactEmail || 'N/A'})`, 55, 190);

  // Executive Metrics Grid
  let y = 235;
  const cardWidth = (doc.page.width - 80 - 30) / 4;
  const verifiedRevenue = payments.reduce((acc, p) => p.status === 'verified' ? acc + parseFloat(p.amount || 0) : acc, 0);
  const checkedInCount = participants.filter(p => p.checkedIn).length;

  const metrics = [
    { label: 'CAPACITY', val: `${event.maxParticipants || 100} Seats` },
    { label: 'REGISTERED', val: `${participants.length}` },
    { label: 'ATTENDANCE', val: `${checkedInCount} Present` },
    { label: 'REVENUE', val: formatCurrency(verifiedRevenue) }
  ];

  metrics.forEach((m, idx) => {
    const x = 40 + idx * (cardWidth + 10);
    doc.rect(x, y, cardWidth, 48).fillAndStroke('#f1f5f9', '#e2e8f0');
    doc.fillColor('#64748b').fontSize(7.5).font('Helvetica-Bold').text(m.label, x + 10, y + 8);
    doc.fillColor('#1e3a8a').fontSize(12).font('Helvetica-Bold').text(m.val, x + 10, y + 24);
  });

  // Participant Roster Table Title
  y = 300;
  doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text('Complete Participant Roster', 40, y);

  y += 18;
  const drawTableHeader = (startY) => {
    doc.rect(40, startY, doc.page.width - 80, 20).fill('#334155');
    doc.fillColor('#ffffff').fontSize(7.5).font('Helvetica-Bold');
    doc.text('PASS ID', 45, startY + 6, { width: 90 });
    doc.text('STUDENT NAME', 140, startY + 6, { width: 130 });
    doc.text('DEPARTMENT', 275, startY + 6, { width: 110 });
    doc.text('STATUS', 390, startY + 6, { width: 60 });
    doc.text('CHECK-IN', 455, startY + 6, { width: 55 });
  };

  drawTableHeader(y);
  y += 20;

  // Render ALL participants across pages
  participants.forEach((p, idx) => {
    // Check if new page is needed
    if (y > doc.page.height - 60) {
      doc.addPage();
      y = 40;
      drawTableHeader(y);
      y += 20;
    }

    const bg = idx % 2 === 0 ? '#ffffff' : '#f8fafc';
    doc.rect(40, y, doc.page.width - 80, 18).fillAndStroke(bg, '#f1f5f9');
    doc.fillColor('#1e293b').fontSize(7.5).font('Helvetica');

    doc.text(p.registrationId || p.registration_id || `REG-${p.id}`, 45, y + 5, { width: 90 });
    doc.text(p.studentName || 'Student', 140, y + 5, { width: 130 });
    doc.text(p.departmentName || 'General', 275, y + 5, { width: 110 });
    doc.text((p.status || 'CONFIRMED').toUpperCase(), 390, y + 5, { width: 60 });
    doc.fillColor(p.checkedIn ? '#059669' : '#94a3b8').font('Helvetica-Bold');
    doc.text(p.checkedIn ? 'PRESENT' : 'ABSENT', 455, y + 5, { width: 55 });
    doc.font('Helvetica');

    y += 18;
  });

  // Feedback Summary Section
  if (feedbackSummary && feedbackSummary.totalResponses > 0) {
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 40;
    } else {
      y += 15;
    }

    doc.rect(40, y, doc.page.width - 80, 50).fillAndStroke('#eff6ff', '#bfdbfe');
    doc.fillColor('#1e40af').fontSize(10).font('Helvetica-Bold').text('Verified Attendee Feedback Summary', 55, y + 10);
    doc.fillColor('#1e3a8a').fontSize(8.5).font('Helvetica');
    doc.text(
      `Total Responses: ${feedbackSummary.totalResponses}   |   Institutional Satisfaction Rating: ${feedbackSummary.averageRating} / 5.0 ⭐`,
      55,
      y + 28
    );
  }

  // Footer on final page
  doc.rect(0, doc.page.height - 30, doc.page.width, 30).fill('#f8fafc');
  doc.fillColor('#94a3b8').fontSize(7.5).font('Helvetica').text(
    `Accreditation report generated on ${new Date().toLocaleString()} • College Event Management System (Smart CEMS)`,
    40,
    doc.page.height - 18,
    { align: 'center', width: doc.page.width - 80 }
  );

  doc.end();
};

/**
 * Generate Student Registration Pass / Ticket with Scannable QR Code
 */
const generateRegistrationReceipt = async (registration, res) => {
  const doc = new PDFDocument({ margin: 30, size: 'A5', layout: 'landscape' });
  doc.pipe(res);

  const regCode = registration.registrationId || registration.registration_id;

  // Generate Scannable QR Code Buffer
  const qrBuffer = await QRCode.toBuffer(regCode, {
    width: 140,
    margin: 1,
    color: { dark: '#1e3a8a', light: '#ffffff' }
  });

  const width = doc.page.width;
  const height = doc.page.height;

  // Outer Decorative Border
  doc.rect(15, 15, width - 30, height - 30).lineWidth(2).stroke('#3b82f6');
  doc.rect(15, 15, width - 30, 48).fill('#1e3a8a');

  doc.fillColor('#ffffff').fontSize(15).font('Helvetica-Bold').text('CAMPUS EVENT PASS & GATE E-TICKET', 30, 24);
  doc.fontSize(8.5).font('Helvetica').text('College Event Management System (Smart CEMS) • Official Gate Admission', 30, 42);

  // Left Section: Event & Student Info
  const startY = 80;
  doc.fillColor('#0f172a').fontSize(14).font('Helvetica-Bold').text(registration.event_title || registration.eventTitle || 'Campus Event', 30, startY, { width: 330 });

  doc.fillColor('#475569').fontSize(9).font('Helvetica');
  doc.text(`Date: ${registration.event_date || registration.date || 'TBA'}   |   Time: ${registration.event_start_time || registration.startTime || 'TBA'}`, 30, startY + 24);
  doc.text(`Venue: ${registration.venue || 'Campus Auditorium'} ${registration.room_number ? `(${registration.room_number})` : ''}`, 30, startY + 38);

  // Attendee Info Box
  doc.rect(30, startY + 58, 330, 80).fillAndStroke('#f8fafc', '#e2e8f0');
  doc.fillColor('#1e293b').fontSize(8).font('Helvetica-Bold').text('ATTENDEE PARTICIPANT DETAILS', 40, startY + 66);
  doc.font('Helvetica').fontSize(8.5).fillColor('#334155');
  doc.text(`Name: ${registration.studentName || registration.student_name}`, 40, startY + 80);
  doc.text(`Student ID / Roll: ${registration.studentRollId || registration.student_roll_id || 'N/A'}`, 40, startY + 94);
  doc.text(`Department: ${registration.departmentName || registration.department_name || 'General'}`, 40, startY + 108);
  doc.text(`Status: ${(registration.status || 'CONFIRMED').toUpperCase()}`, 40, startY + 122);

  // Right Section: QR Code & Pass Identifier Box
  const qrX = width - 180;
  doc.rect(qrX, startY, 150, 175).fillAndStroke('#f1f5f9', '#cbd5e1');

  doc.image(qrBuffer, qrX + 10, startY + 10, { width: 130 });

  doc.fillColor('#4f46e5').fontSize(8).font('Helvetica-Bold').text('PASS IDENTIFIER', qrX + 10, startY + 144, { width: 130, align: 'center' });
  doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold').text(regCode, qrX + 10, startY + 156, { width: 130, align: 'center' });

  // Gate Scan Warning Footer
  doc.fillColor('#94a3b8').fontSize(7).font('Helvetica-Oblique').text(
    'Please present this digital pass or printed slip at the venue entrance. Scanner verifies attendance live.',
    30,
    height - 28,
    { width: width - 60, align: 'center' }
  );

  doc.end();
};

module.exports = {
  generateEventReport,
  generateRegistrationReceipt
};
